### ISSUE TITLE
"Download Nach"-Option für Audio aus Online-Quellen

### ISSUE THREAD

**Issue by MartinRied** [JoergRue/Ares#11]
Es sollte auch möglich sein, Sounds o.Ä. aus Online-Quellen in ein selbst gewähltes Verzeichnis herunterzuladen.
Eine passende Option ist im Kontext-Menü der Suchergebnisse bereits vorgesehen, momentan allerdings ausgeblendet.
Eventuell wird diese Funktionalität auch gar nicht gebraucht, wenn #5 umgesetzt wird...

**Comment by JoergRue** [comment]
Implementiert.
