### ISSUE TITLE
3.1.0, Player - Falsche Anzeige (Einstellungen > Musik)

### ISSUE THREAD

**Issue by Johmi** [JoergRue/Ares#13]
Ares Player > Einstellungen > Musik > "Blenden wenn die Musik manuell geändert wird"

Die Einstellungen werden korrekt in der XML-Datei gespeichert und im Controller auch korrekt angezeigt. Im Player ist jedoch immer "Ausblenden dann einblenden" angewählt.
Die "Blendzeit" wird auch im Player korrekt angezeigt.

**Comment by JoergRue** [comment]
Kann ich nicht nachvollziehen -- bei mir zeigt der Player immer das an, was ich vorher entweder im Player oder im Controller eingestellt habe.

**Comment by Johmi** [comment]
Ja, komisch... jetzt funktioniert das bei mir auch. O_o Ich bin verwirrt.

Bein meinen Versuchen den Fehler zu rekonstruieren ist mir nebenbei aufgefallen, dass (beim Speicherpfad der Settings) immer die Einstellungen des zuletzt geschlossenen Programmteils übernommen werden. Ändere ich also etwas im Player, schließe diesen und schließe danach den Editor, dann werden die neuen Settings aus dem Player mit den alten aus dem Editor überschrieben.
Das ist natürlich nur ein kleiner Schönheitsfehler und ändert nichts daran, dass Ares der absolute Hammer ist!  :D

**Comment by JoergRue** [comment]
Tatsächlich lädt das eine Programm die Einstellungen neu wenn sie im anderen Programm geändert wurden (wenn's klappt) und dadurch wird nichts überschrieben. Nur wenn man ausgerechnet den Speicherpfad der Einstellungen ändert, funktioniert das halt nicht.
