### ISSUE TITLE
Musik-Überblenden beim Wechsel eines Modus

### ISSUE THREAD

**Issue by Johmi** [JoergRue/Ares#14]
Ich bin mir nicht sicher ob Bug oder Feature... ;)

Ich habe 2 Szenarien in einem Modus, jeweils mit einer Sequentiellen Musikliste. Bei den Stücken ist immer ein Fade-In und Fade-Out hinterlegt, die Option "Überblenden" ist aktiviert. Wenn ich innerhalb eines Szenario ein Lied überspringe, dann wird übergeblendet.
Beim Wechsel des Szenarios erfolgt aber immer ein harter Schnitt: Das Lied des neuen Szenarios endet aprupt, das Lied des neuen Szenarios wird in die entstandene Stille eingeblendet.

Ein sanftes Überblenden wäre deutlich schöner. :)

**Comment by JoergRue** [comment]
Das ist ein Feature ;-).

Das Fading bei den einzelnen Stücken gilt nur für den Fall, dass man innerhalb der Liste bleibt. Beim Umschalten auf ein anderes Szenario stellt man das Fading in der Startoptionen des Szenarios ein (Rechtsklick auf das Szenario und "Start..." auswählen). 

Grund ist, dass man beim Wechsel auf manche Szenarien einen harten Schnitt will (es passiert plötzlich etwas), selbst wenn man normalerweise blendet.
