### ISSUE TITLE
Drag & Drop von Dateien aus Online-Quelle in den File- bzw. Music-Explorer

### ISSUE THREAD

**Issue by MartinRied** [JoergRue/Ares#5]
Sehr praktisch wäre, wenn man die Suchergebnisse dann nicht nur direkt ins Projekt, sondern auch in einen Ordner im File- bzw. Music Explorer ziehen könnte.

**Comment by MartinRied** [comment]
Ich würde dieses Thema gerne zurückstellen, damit ich die Grundfunktionalität erst einmal abschließen kann.

**Comment by JoergRue** [comment]
Implementiert.
